### ISSUE TITLE
EDA issue

### ISSUE THREAD

**Issue by merveshin** [UBC-MDS/DSCI_522_G410#12]
The current EDA file was somehow corrupted when I was committing to the repository. I replaced file and added more wrangling. I had to clear all cell outputs to reduce file size below 25MB. You can run cells to get graphs. Please consider EDA file in this pull request: https://github.com/UBC-MDS/DSCI_522_G410/pull/11

**Comment by merveshin** [comment]
There is another EDA file in the src repo, it was the ex file so you can discard it

**Comment by eyrakas** [comment]
You are right, there is an old EDA file in src folder. I will remove it if that is okay.

**Comment by merveshin** [comment]
I think we don’t need it anymore, if the new version is working on your
repo.

**Comment by eyrakas** [comment]
Removed the old one. Sent new PR for merging.

**Comment by hwilliams10** [comment]
> The current EDA file was somehow corrupted when I was committing to the repository. I replaced file and added more wrangling. I had to clear all cell outputs to reduce file size below 25MB. You can run cells to get graphs. Please consider EDA file in this pull request: #11

Ah that explains it. I wonder if the file size will be smaller if we save the figures and import them into a `.md` file? I'm happy to try this tomorrow morning and try and get a file that renders nicely on GitHub that we can link to for milestone 1.

**Comment by eyrakas** [comment]
> > The current EDA file was somehow corrupted when I was committing to the repository. I replaced file and added more wrangling. I had to clear all cell outputs to reduce file size below 25MB. You can run cells to get graphs. Please consider EDA file in this pull request: #11
> 
> Ah that explains it. I wonder if the file size will be smaller if we save the figures and import them into a `.md` file? I'm happy to try this tomorrow morning and try and get a file that renders nicely on GitHub that we can link to for milestone 1.

I have created new `img` folder with all the graphs, that reduced the EDA file size.

**Comment by hwilliams10** [comment]
Ahh I just finished doing the same thing...and reorganizing the file structure. Darn.
I will retract my pull request because there will be a ton of merge issues.. 

Just for general cleaning, I think we should
 - move the .csv file to a `data` folder 
- move `EDA.ipynb` to `src`
