### ISSUE TITLE
Save download scripts

### ISSUE THREAD

**Issue by hwilliams10** [UBC-MDS/DSCI_522_G410#23]
Hey @mglu123 ,

Thanks for fixing the save_download script. I noticed that the code below splits the data based on a non-random index:
```
data_fifa <- read.csv(url)
  num_rows <- dim(data_fifa)[1] - dim(data_fifa)[[1]]%/%5
  data_fifa_train <- data_fifa[1:num_rows,]
  data_fifa_test <- data_fifa[num_rows:dim(data_fifa)[1],]
```

I think this might be an issue (since the data is sorted by rating, we will be putting all the lowest rated players in our test set and our test and train sets won't be truly representative).
Can we try to make the split more balanced? Maybe something like the below from Tiffany's example:
```# split into training and test data sets
  training_rows <- raw_data %>% 
    select(class) %>% 
    pull() %>%
    createDataPartition(p = 0.75, list = FALSE)
  training_data <- raw_data %>% slice(training_rows)
  test_data <- raw_data %>% slice(-training_rows)
```

Source: https://github.com/ttimbers/breast_cancer_predictor/blob/9c19bd6ea34f76025218845db404bf13140b5c94/src/pre_process_wisc.r

**Comment by mglu123** [comment]
Good point! I have changed that.
