### ISSUE TITLE
Issue: Running Analysis Script on Command Line

### ISSUE THREAD

**Issue by eyrakas** [UBC-MDS/DSCI_522_G410#28]
script = https://github.com/UBC-MDS/DSCI_522_G410/blob/master/src/analysis.py 
Jupyter = https://github.com/UBC-MDS/DSCI_522_G410/blob/master/src/analysis.ipynb

code runs fine with Jupyter and saves results BUT nothing happens when script is run on the command line, any thoughts? @mglu123 @merveshin @hwilliams10

**Comment by hwilliams10** [comment]
What is the line of code you are running on the command line and what errors are you getting?

**Comment by eyrakas** [comment]
(while current working directory is src folder):
command line code:
python analysis.py --train_data_path="../data/cleaned/clean_train.csv" --test_data_path="../data/cleaned/clean_test.csv" --results_path="../results"

**Comment by eyrakas** [comment]
It doesn't throw an error and doesn't produce to results folder.

**Comment by hwilliams10** [comment]
Did you try fixing this error:
```Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)```
