### ISSUE TITLE
Peer Feedback - Aman/Karan

### ISSUE THREAD

**Issue by eyrakas** [UBC-MDS/DSCI_522_G410#40]
Hi everyone,
There was only one minor suggestion that was put forward by my peers. This is as below:

- Directory re-organization.
(Re-organize the scripts folder into separate folders based on what each script is doing).

**Comment by hwilliams10** [comment]
As a group, we have discussed this comment and since there are not that many scripts we think it is cleaner to have one `src` directory rather than creating a bunch of extra sub-folders that only hold 1 or 2 scripts.
