### ISSUE TITLE
Path in your usage should not be a local path..

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_G410#51]
I was trying to reproduce some of your analysis to help troubleshoot and noticed this:

```
# 1. Downloads, saves, and splits FIFA data: note absolute paths should be replaced with user-specific path
RScript .\src\save_download.R --'/Users/huayuelu/Desktop/DSCI_522_G410/data/fifa_data_train.csv' --'/Users/huayuelu/Desktop/DSCI_522_G410/data/fifa_data_test.csv'  --https://raw.githubusercontent.com/mglu123/live_dash_demo/master/data-2.csv
```

You should not run these scripts with files referenced outside of the repo

**Comment by hwilliams10** [comment]
Got it. That was the first thing we fixed this week. It does work with relative paths now, and it has been updated in our makefile accordingly.
