### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_G410#56]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice
- - [x] Table 1:
	- - [x] Too many sig figs, there's no need to show that many, it hurts readability and interpretability
- - [x] Table 2:
	- - [ ] Great!
- - [x] Figure 1:
	- - [x] This is tricky data to show, and it's great you've managed to find a way to show this as effectively as you have.
	- - [x] Should be very careful about doing a box-plot on a log-scaled data; you note this in your text about how the differences are actually more pronounced than they appear, but I wonder if there is a better way?
	- - [x] I don't have any good ideas for you yet - maybe flag me during lab and you can walk me through what you've tried already?
	- - [x] The y-axis label is pretty complex, could you put some of that information in the title so it's easier to read?
- - [x] Overall, great work! I think your tables and figure overall are very reasonable for your project and well-selected.

**Comment by hwilliams10** [comment]
Report figures updated based on lab discussions and figures in the first table have been rounded for readability.
