### ISSUE TITLE
EDA process

### ISSUE THREAD

**Issue by merveshin** [UBC-MDS/DSCI_522_G410#6]
So far I split the data set at the very beginning and made some wrangling only for training set. I just dropped the NAN's because there are too many, but maybe we can think another solution later. I couldn't add the names of the outliers on the distribution of the wage plot but I am working on it. Do you have any other suggestions about the graphs?

**Comment by mglu123** [comment]
Hi, I might make a overlap error here. Delating the line '  size = 'Potential',' will be better


 alt.Chart(df).mark_point().encode(
    x='Age',
    y='Overall',
    size = 'Potential',
)

I think it will be fine that we don't add names of the outliers in the stage of EDA. 
Adding axises labels and titles of graph might be more helpful

**Comment by merveshin** [comment]
I am considering that instead of adding the names of the outliers on the graph, I will make a separate table to show the outliers and their attributes, clubs. We can show the wage distribution is highly skewed because of those names and I feel like looking at their attributes will be good.

**Comment by hwilliams10** [comment]
> I am considering that instead of adding the names of the outliers on the graph, I will make a separate table to show the outliers and their attributes, clubs. We can show the wage distribution is highly skewed because of those names and I feel like looking at their attributes will be good.

I think that sounds like a good option!

**Comment by hwilliams10** [comment]
Hey @merveshin,

On a related note, I merged your last pull request but when I tried to open the `EDA.ipynb` notebook the file seemed to be corrupted and wouldn't open. Does this happen for anyone else?

**Comment by merveshin** [comment]
Yeah. After your merge, I noticed that it is broken I couldn’t understand
why but now I am working on it and try to write the codes again.

Btw, I added the ‘BMI’ column and prepared the plots : age Vs wage, Overall
Vs wage, BMI vs age

After completing this new version, I will send it to you.

**Comment by eyrakas** [comment]
I have just merged the PR from Mervin. I think it is working now.
